services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: coyoacan_postgis
    restart: always
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../data:/data
    networks:
      - coyoacan_network
    ports:
      - "${POSTGRES_PORT}:5432"

  coyoacan_dash_app:
    build:
      context: ../app
      dockerfile: Dockerfile
    container_name: coyoacan_dash_app
    restart: always
    env_file:
      - ../.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "${DASH_PORT}:8050"
    depends_on:
      - db
    networks:
      - coyoacan_network

networks:
  coyoacan_network:

volumes:
  postgres_data:
